// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginOnline.proto

package org.qiunet.tests.proto;

public final class LoginOnlineProto {
  private LoginOnlineProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginOnlineRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginOnlineRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RequestHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.RequestHeader header = 1;</code>
     * @return The header.
     */
    org.qiunet.tests.proto.HeaderProto.RequestHeader getHeader();
    /**
     * <code>.RequestHeader header = 1;</code>
     */
    org.qiunet.tests.proto.HeaderProto.RequestHeaderOrBuilder getHeaderOrBuilder();
  }
  /**
   * Protobuf type {@code LoginOnlineRequest}
   */
  public  static final class LoginOnlineRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginOnlineRequest)
      LoginOnlineRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginOnlineRequest.newBuilder() to construct.
    private LoginOnlineRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginOnlineRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginOnlineRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginOnlineRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.qiunet.tests.proto.HeaderProto.RequestHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(org.qiunet.tests.proto.HeaderProto.RequestHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qiunet.tests.proto.LoginOnlineProto.internal_static_LoginOnlineRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qiunet.tests.proto.LoginOnlineProto.internal_static_LoginOnlineRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest.class, org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private org.qiunet.tests.proto.HeaderProto.RequestHeader header_;
    /**
     * <code>.RequestHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.RequestHeader header = 1;</code>
     * @return The header.
     */
    public org.qiunet.tests.proto.HeaderProto.RequestHeader getHeader() {
      return header_ == null ? org.qiunet.tests.proto.HeaderProto.RequestHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.RequestHeader header = 1;</code>
     */
    public org.qiunet.tests.proto.HeaderProto.RequestHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest)) {
        return super.equals(obj);
      }
      org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest other = (org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginOnlineRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginOnlineRequest)
        org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.qiunet.tests.proto.LoginOnlineProto.internal_static_LoginOnlineRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.qiunet.tests.proto.LoginOnlineProto.internal_static_LoginOnlineRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest.class, org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest.Builder.class);
      }

      // Construct using org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.qiunet.tests.proto.LoginOnlineProto.internal_static_LoginOnlineRequest_descriptor;
      }

      @java.lang.Override
      public org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest getDefaultInstanceForType() {
        return org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest build() {
        org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest buildPartial() {
        org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest result = new org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest) {
          return mergeFrom((org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest other) {
        if (other == org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.qiunet.tests.proto.HeaderProto.RequestHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.qiunet.tests.proto.HeaderProto.RequestHeader, org.qiunet.tests.proto.HeaderProto.RequestHeader.Builder, org.qiunet.tests.proto.HeaderProto.RequestHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.RequestHeader header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       * @return The header.
       */
      public org.qiunet.tests.proto.HeaderProto.RequestHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? org.qiunet.tests.proto.HeaderProto.RequestHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder setHeader(org.qiunet.tests.proto.HeaderProto.RequestHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder setHeader(
          org.qiunet.tests.proto.HeaderProto.RequestHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder mergeHeader(org.qiunet.tests.proto.HeaderProto.RequestHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              org.qiunet.tests.proto.HeaderProto.RequestHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public org.qiunet.tests.proto.HeaderProto.RequestHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public org.qiunet.tests.proto.HeaderProto.RequestHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              org.qiunet.tests.proto.HeaderProto.RequestHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.qiunet.tests.proto.HeaderProto.RequestHeader, org.qiunet.tests.proto.HeaderProto.RequestHeader.Builder, org.qiunet.tests.proto.HeaderProto.RequestHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.qiunet.tests.proto.HeaderProto.RequestHeader, org.qiunet.tests.proto.HeaderProto.RequestHeader.Builder, org.qiunet.tests.proto.HeaderProto.RequestHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LoginOnlineRequest)
    }

    // @@protoc_insertion_point(class_scope:LoginOnlineRequest)
    private static final org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest();
    }

    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginOnlineRequest>
        PARSER = new com.google.protobuf.AbstractParser<LoginOnlineRequest>() {
      @java.lang.Override
      public LoginOnlineRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginOnlineRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginOnlineRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginOnlineRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginOnlineResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginOnlineResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ResponseHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.ResponseHeader header = 1;</code>
     * @return The header.
     */
    org.qiunet.tests.proto.HeaderProto.ResponseHeader getHeader();
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    org.qiunet.tests.proto.HeaderProto.ResponseHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <pre>
     * 需要一个数字. 否则没有东西序列化出来
     * </pre>
     *
     * <code>int32 day = 2;</code>
     * @return The day.
     */
    int getDay();
  }
  /**
   * <pre>
   * 登录请求响应
   * </pre>
   *
   * Protobuf type {@code LoginOnlineResponse}
   */
  public  static final class LoginOnlineResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginOnlineResponse)
      LoginOnlineResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginOnlineResponse.newBuilder() to construct.
    private LoginOnlineResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginOnlineResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginOnlineResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginOnlineResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.qiunet.tests.proto.HeaderProto.ResponseHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(org.qiunet.tests.proto.HeaderProto.ResponseHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              day_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qiunet.tests.proto.LoginOnlineProto.internal_static_LoginOnlineResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qiunet.tests.proto.LoginOnlineProto.internal_static_LoginOnlineResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse.class, org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private org.qiunet.tests.proto.HeaderProto.ResponseHeader header_;
    /**
     * <code>.ResponseHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.ResponseHeader header = 1;</code>
     * @return The header.
     */
    public org.qiunet.tests.proto.HeaderProto.ResponseHeader getHeader() {
      return header_ == null ? org.qiunet.tests.proto.HeaderProto.ResponseHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    public org.qiunet.tests.proto.HeaderProto.ResponseHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int DAY_FIELD_NUMBER = 2;
    private int day_;
    /**
     * <pre>
     * 需要一个数字. 否则没有东西序列化出来
     * </pre>
     *
     * <code>int32 day = 2;</code>
     * @return The day.
     */
    public int getDay() {
      return day_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (day_ != 0) {
        output.writeInt32(2, day_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (day_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, day_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse)) {
        return super.equals(obj);
      }
      org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse other = (org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (getDay()
          != other.getDay()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + getDay();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 登录请求响应
     * </pre>
     *
     * Protobuf type {@code LoginOnlineResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginOnlineResponse)
        org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.qiunet.tests.proto.LoginOnlineProto.internal_static_LoginOnlineResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.qiunet.tests.proto.LoginOnlineProto.internal_static_LoginOnlineResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse.class, org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse.Builder.class);
      }

      // Construct using org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        day_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.qiunet.tests.proto.LoginOnlineProto.internal_static_LoginOnlineResponse_descriptor;
      }

      @java.lang.Override
      public org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse getDefaultInstanceForType() {
        return org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse build() {
        org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse buildPartial() {
        org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse result = new org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.day_ = day_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse) {
          return mergeFrom((org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse other) {
        if (other == org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getDay() != 0) {
          setDay(other.getDay());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.qiunet.tests.proto.HeaderProto.ResponseHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.qiunet.tests.proto.HeaderProto.ResponseHeader, org.qiunet.tests.proto.HeaderProto.ResponseHeader.Builder, org.qiunet.tests.proto.HeaderProto.ResponseHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.ResponseHeader header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       * @return The header.
       */
      public org.qiunet.tests.proto.HeaderProto.ResponseHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? org.qiunet.tests.proto.HeaderProto.ResponseHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder setHeader(org.qiunet.tests.proto.HeaderProto.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder setHeader(
          org.qiunet.tests.proto.HeaderProto.ResponseHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder mergeHeader(org.qiunet.tests.proto.HeaderProto.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              org.qiunet.tests.proto.HeaderProto.ResponseHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public org.qiunet.tests.proto.HeaderProto.ResponseHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public org.qiunet.tests.proto.HeaderProto.ResponseHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              org.qiunet.tests.proto.HeaderProto.ResponseHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.qiunet.tests.proto.HeaderProto.ResponseHeader, org.qiunet.tests.proto.HeaderProto.ResponseHeader.Builder, org.qiunet.tests.proto.HeaderProto.ResponseHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.qiunet.tests.proto.HeaderProto.ResponseHeader, org.qiunet.tests.proto.HeaderProto.ResponseHeader.Builder, org.qiunet.tests.proto.HeaderProto.ResponseHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private int day_ ;
      /**
       * <pre>
       * 需要一个数字. 否则没有东西序列化出来
       * </pre>
       *
       * <code>int32 day = 2;</code>
       * @return The day.
       */
      public int getDay() {
        return day_;
      }
      /**
       * <pre>
       * 需要一个数字. 否则没有东西序列化出来
       * </pre>
       *
       * <code>int32 day = 2;</code>
       * @param value The day to set.
       * @return This builder for chaining.
       */
      public Builder setDay(int value) {
        
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 需要一个数字. 否则没有东西序列化出来
       * </pre>
       *
       * <code>int32 day = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDay() {
        
        day_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LoginOnlineResponse)
    }

    // @@protoc_insertion_point(class_scope:LoginOnlineResponse)
    private static final org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse();
    }

    public static org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginOnlineResponse>
        PARSER = new com.google.protobuf.AbstractParser<LoginOnlineResponse>() {
      @java.lang.Override
      public LoginOnlineResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginOnlineResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginOnlineResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginOnlineResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.qiunet.tests.proto.LoginOnlineProto.LoginOnlineResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginOnlineRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginOnlineRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginOnlineResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginOnlineResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021LoginOnline.proto\032\014Header.proto\"4\n\022Log" +
      "inOnlineRequest\022\036\n\006header\030\001 \001(\0132\016.Reques" +
      "tHeader\"C\n\023LoginOnlineResponse\022\037\n\006header" +
      "\030\001 \001(\0132\017.ResponseHeader\022\013\n\003day\030\002 \001(\005B*\n\026" +
      "org.qiunet.tests.protoB\020LoginOnlineProto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.qiunet.tests.proto.HeaderProto.getDescriptor(),
        });
    internal_static_LoginOnlineRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginOnlineRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginOnlineRequest_descriptor,
        new java.lang.String[] { "Header", });
    internal_static_LoginOnlineResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginOnlineResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginOnlineResponse_descriptor,
        new java.lang.String[] { "Header", "Day", });
    org.qiunet.tests.proto.HeaderProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
