// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/login.proto

package org.qiunet.flash.handler.proto;

public final class LoginProto {
  private LoginProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 平台的 openid
     * </pre>
     *
     * <code>string openid = 1;</code>
     */
    java.lang.String getOpenid();
    /**
     * <pre>
     * 平台的 openid
     * </pre>
     *
     * <code>string openid = 1;</code>
     */
    com.google.protobuf.ByteString
        getOpenidBytes();

    /**
     * <pre>
     * 选服时下发的token
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <pre>
     * 选服时下发的token
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code LoginRequest}
   */
  public  static final class LoginRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginRequest)
      LoginRequestOrBuilder {
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginRequest() {
      openid_ = "";
      token_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              openid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qiunet.flash.handler.proto.LoginProto.internal_static_LoginRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qiunet.flash.handler.proto.LoginProto.internal_static_LoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qiunet.flash.handler.proto.LoginProto.LoginRequest.class, org.qiunet.flash.handler.proto.LoginProto.LoginRequest.Builder.class);
    }

    public static final int OPENID_FIELD_NUMBER = 1;
    private volatile java.lang.Object openid_;
    /**
     * <pre>
     * 平台的 openid
     * </pre>
     *
     * <code>string openid = 1;</code>
     */
    public java.lang.String getOpenid() {
      java.lang.Object ref = openid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        openid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 平台的 openid
     * </pre>
     *
     * <code>string openid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOpenidBytes() {
      java.lang.Object ref = openid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        openid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <pre>
     * 选服时下发的token
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 选服时下发的token
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOpenidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, openid_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOpenidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, openid_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.qiunet.flash.handler.proto.LoginProto.LoginRequest)) {
        return super.equals(obj);
      }
      org.qiunet.flash.handler.proto.LoginProto.LoginRequest other = (org.qiunet.flash.handler.proto.LoginProto.LoginRequest) obj;

      boolean result = true;
      result = result && getOpenid()
          .equals(other.getOpenid());
      result = result && getToken()
          .equals(other.getToken());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPENID_FIELD_NUMBER;
      hash = (53 * hash) + getOpenid().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.qiunet.flash.handler.proto.LoginProto.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.qiunet.flash.handler.proto.LoginProto.LoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginRequest)
        org.qiunet.flash.handler.proto.LoginProto.LoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.qiunet.flash.handler.proto.LoginProto.internal_static_LoginRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.qiunet.flash.handler.proto.LoginProto.internal_static_LoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.qiunet.flash.handler.proto.LoginProto.LoginRequest.class, org.qiunet.flash.handler.proto.LoginProto.LoginRequest.Builder.class);
      }

      // Construct using org.qiunet.flash.handler.proto.LoginProto.LoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        openid_ = "";

        token_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.qiunet.flash.handler.proto.LoginProto.internal_static_LoginRequest_descriptor;
      }

      public org.qiunet.flash.handler.proto.LoginProto.LoginRequest getDefaultInstanceForType() {
        return org.qiunet.flash.handler.proto.LoginProto.LoginRequest.getDefaultInstance();
      }

      public org.qiunet.flash.handler.proto.LoginProto.LoginRequest build() {
        org.qiunet.flash.handler.proto.LoginProto.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.qiunet.flash.handler.proto.LoginProto.LoginRequest buildPartial() {
        org.qiunet.flash.handler.proto.LoginProto.LoginRequest result = new org.qiunet.flash.handler.proto.LoginProto.LoginRequest(this);
        result.openid_ = openid_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.qiunet.flash.handler.proto.LoginProto.LoginRequest) {
          return mergeFrom((org.qiunet.flash.handler.proto.LoginProto.LoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.qiunet.flash.handler.proto.LoginProto.LoginRequest other) {
        if (other == org.qiunet.flash.handler.proto.LoginProto.LoginRequest.getDefaultInstance()) return this;
        if (!other.getOpenid().isEmpty()) {
          openid_ = other.openid_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.qiunet.flash.handler.proto.LoginProto.LoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.qiunet.flash.handler.proto.LoginProto.LoginRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object openid_ = "";
      /**
       * <pre>
       * 平台的 openid
       * </pre>
       *
       * <code>string openid = 1;</code>
       */
      public java.lang.String getOpenid() {
        java.lang.Object ref = openid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          openid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 平台的 openid
       * </pre>
       *
       * <code>string openid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOpenidBytes() {
        java.lang.Object ref = openid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          openid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 平台的 openid
       * </pre>
       *
       * <code>string openid = 1;</code>
       */
      public Builder setOpenid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        openid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 平台的 openid
       * </pre>
       *
       * <code>string openid = 1;</code>
       */
      public Builder clearOpenid() {
        
        openid_ = getDefaultInstance().getOpenid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 平台的 openid
       * </pre>
       *
       * <code>string openid = 1;</code>
       */
      public Builder setOpenidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        openid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       * 选服时下发的token
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 选服时下发的token
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 选服时下发的token
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 选服时下发的token
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 选服时下发的token
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:LoginRequest)
    }

    // @@protoc_insertion_point(class_scope:LoginRequest)
    private static final org.qiunet.flash.handler.proto.LoginProto.LoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.qiunet.flash.handler.proto.LoginProto.LoginRequest();
    }

    public static org.qiunet.flash.handler.proto.LoginProto.LoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginRequest>
        PARSER = new com.google.protobuf.AbstractParser<LoginRequest>() {
      public LoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRequest> getParserForType() {
      return PARSER;
    }

    public org.qiunet.flash.handler.proto.LoginProto.LoginRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * uid
     * </pre>
     *
     * <code>int32 uid = 1;</code>
     */
    int getUid();

    /**
     * <pre>
     * 需要注册 true  不需要 false
     * </pre>
     *
     * <code>bool needRegister = 2;</code>
     */
    boolean getNeedRegister();
  }
  /**
   * <pre>
   * 登录请求响应
   * </pre>
   *
   * Protobuf type {@code LoginResponse}
   */
  public  static final class LoginResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginResponse)
      LoginResponseOrBuilder {
    // Use LoginResponse.newBuilder() to construct.
    private LoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginResponse() {
      uid_ = 0;
      needRegister_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoginResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              uid_ = input.readInt32();
              break;
            }
            case 16: {

              needRegister_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qiunet.flash.handler.proto.LoginProto.internal_static_LoginResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qiunet.flash.handler.proto.LoginProto.internal_static_LoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qiunet.flash.handler.proto.LoginProto.LoginResponse.class, org.qiunet.flash.handler.proto.LoginProto.LoginResponse.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <pre>
     * uid
     * </pre>
     *
     * <code>int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int NEEDREGISTER_FIELD_NUMBER = 2;
    private boolean needRegister_;
    /**
     * <pre>
     * 需要注册 true  不需要 false
     * </pre>
     *
     * <code>bool needRegister = 2;</code>
     */
    public boolean getNeedRegister() {
      return needRegister_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0) {
        output.writeInt32(1, uid_);
      }
      if (needRegister_ != false) {
        output.writeBool(2, needRegister_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (needRegister_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, needRegister_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.qiunet.flash.handler.proto.LoginProto.LoginResponse)) {
        return super.equals(obj);
      }
      org.qiunet.flash.handler.proto.LoginProto.LoginResponse other = (org.qiunet.flash.handler.proto.LoginProto.LoginResponse) obj;

      boolean result = true;
      result = result && (getUid()
          == other.getUid());
      result = result && (getNeedRegister()
          == other.getNeedRegister());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (37 * hash) + NEEDREGISTER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNeedRegister());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.qiunet.flash.handler.proto.LoginProto.LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.qiunet.flash.handler.proto.LoginProto.LoginResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 登录请求响应
     * </pre>
     *
     * Protobuf type {@code LoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginResponse)
        org.qiunet.flash.handler.proto.LoginProto.LoginResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.qiunet.flash.handler.proto.LoginProto.internal_static_LoginResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.qiunet.flash.handler.proto.LoginProto.internal_static_LoginResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.qiunet.flash.handler.proto.LoginProto.LoginResponse.class, org.qiunet.flash.handler.proto.LoginProto.LoginResponse.Builder.class);
      }

      // Construct using org.qiunet.flash.handler.proto.LoginProto.LoginResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = 0;

        needRegister_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.qiunet.flash.handler.proto.LoginProto.internal_static_LoginResponse_descriptor;
      }

      public org.qiunet.flash.handler.proto.LoginProto.LoginResponse getDefaultInstanceForType() {
        return org.qiunet.flash.handler.proto.LoginProto.LoginResponse.getDefaultInstance();
      }

      public org.qiunet.flash.handler.proto.LoginProto.LoginResponse build() {
        org.qiunet.flash.handler.proto.LoginProto.LoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.qiunet.flash.handler.proto.LoginProto.LoginResponse buildPartial() {
        org.qiunet.flash.handler.proto.LoginProto.LoginResponse result = new org.qiunet.flash.handler.proto.LoginProto.LoginResponse(this);
        result.uid_ = uid_;
        result.needRegister_ = needRegister_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.qiunet.flash.handler.proto.LoginProto.LoginResponse) {
          return mergeFrom((org.qiunet.flash.handler.proto.LoginProto.LoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.qiunet.flash.handler.proto.LoginProto.LoginResponse other) {
        if (other == org.qiunet.flash.handler.proto.LoginProto.LoginResponse.getDefaultInstance()) return this;
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (other.getNeedRegister() != false) {
          setNeedRegister(other.getNeedRegister());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.qiunet.flash.handler.proto.LoginProto.LoginResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.qiunet.flash.handler.proto.LoginProto.LoginResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uid_ ;
      /**
       * <pre>
       * uid
       * </pre>
       *
       * <code>int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <pre>
       * uid
       * </pre>
       *
       * <code>int32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * uid
       * </pre>
       *
       * <code>int32 uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }

      private boolean needRegister_ ;
      /**
       * <pre>
       * 需要注册 true  不需要 false
       * </pre>
       *
       * <code>bool needRegister = 2;</code>
       */
      public boolean getNeedRegister() {
        return needRegister_;
      }
      /**
       * <pre>
       * 需要注册 true  不需要 false
       * </pre>
       *
       * <code>bool needRegister = 2;</code>
       */
      public Builder setNeedRegister(boolean value) {
        
        needRegister_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 需要注册 true  不需要 false
       * </pre>
       *
       * <code>bool needRegister = 2;</code>
       */
      public Builder clearNeedRegister() {
        
        needRegister_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:LoginResponse)
    }

    // @@protoc_insertion_point(class_scope:LoginResponse)
    private static final org.qiunet.flash.handler.proto.LoginProto.LoginResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.qiunet.flash.handler.proto.LoginProto.LoginResponse();
    }

    public static org.qiunet.flash.handler.proto.LoginProto.LoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginResponse>
        PARSER = new com.google.protobuf.AbstractParser<LoginResponse>() {
      public LoginResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResponse> getParserForType() {
      return PARSER;
    }

    public org.qiunet.flash.handler.proto.LoginProto.LoginResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FightStartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FightStart)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 战斗的人
     * </pre>
     *
     * <code>repeated int32 uids = 1;</code>
     */
    java.util.List<java.lang.Integer> getUidsList();
    /**
     * <pre>
     * 战斗的人
     * </pre>
     *
     * <code>repeated int32 uids = 1;</code>
     */
    int getUidsCount();
    /**
     * <pre>
     * 战斗的人
     * </pre>
     *
     * <code>repeated int32 uids = 1;</code>
     */
    int getUids(int index);
  }
  /**
   * <pre>
   * 房间准备好了
   * </pre>
   *
   * Protobuf type {@code FightStart}
   */
  public  static final class FightStart extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FightStart)
      FightStartOrBuilder {
    // Use FightStart.newBuilder() to construct.
    private FightStart(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FightStart() {
      uids_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FightStart(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                uids_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              uids_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                uids_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                uids_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          uids_ = java.util.Collections.unmodifiableList(uids_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qiunet.flash.handler.proto.LoginProto.internal_static_FightStart_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qiunet.flash.handler.proto.LoginProto.internal_static_FightStart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qiunet.flash.handler.proto.LoginProto.FightStart.class, org.qiunet.flash.handler.proto.LoginProto.FightStart.Builder.class);
    }

    public static final int UIDS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> uids_;
    /**
     * <pre>
     * 战斗的人
     * </pre>
     *
     * <code>repeated int32 uids = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getUidsList() {
      return uids_;
    }
    /**
     * <pre>
     * 战斗的人
     * </pre>
     *
     * <code>repeated int32 uids = 1;</code>
     */
    public int getUidsCount() {
      return uids_.size();
    }
    /**
     * <pre>
     * 战斗的人
     * </pre>
     *
     * <code>repeated int32 uids = 1;</code>
     */
    public int getUids(int index) {
      return uids_.get(index);
    }
    private int uidsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getUidsList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(uidsMemoizedSerializedSize);
      }
      for (int i = 0; i < uids_.size(); i++) {
        output.writeInt32NoTag(uids_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < uids_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(uids_.get(i));
        }
        size += dataSize;
        if (!getUidsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        uidsMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.qiunet.flash.handler.proto.LoginProto.FightStart)) {
        return super.equals(obj);
      }
      org.qiunet.flash.handler.proto.LoginProto.FightStart other = (org.qiunet.flash.handler.proto.LoginProto.FightStart) obj;

      boolean result = true;
      result = result && getUidsList()
          .equals(other.getUidsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUidsCount() > 0) {
        hash = (37 * hash) + UIDS_FIELD_NUMBER;
        hash = (53 * hash) + getUidsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.qiunet.flash.handler.proto.LoginProto.FightStart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.FightStart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.FightStart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.FightStart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.FightStart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.FightStart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.FightStart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.FightStart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.FightStart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.flash.handler.proto.LoginProto.FightStart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.qiunet.flash.handler.proto.LoginProto.FightStart prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 房间准备好了
     * </pre>
     *
     * Protobuf type {@code FightStart}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FightStart)
        org.qiunet.flash.handler.proto.LoginProto.FightStartOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.qiunet.flash.handler.proto.LoginProto.internal_static_FightStart_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.qiunet.flash.handler.proto.LoginProto.internal_static_FightStart_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.qiunet.flash.handler.proto.LoginProto.FightStart.class, org.qiunet.flash.handler.proto.LoginProto.FightStart.Builder.class);
      }

      // Construct using org.qiunet.flash.handler.proto.LoginProto.FightStart.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.qiunet.flash.handler.proto.LoginProto.internal_static_FightStart_descriptor;
      }

      public org.qiunet.flash.handler.proto.LoginProto.FightStart getDefaultInstanceForType() {
        return org.qiunet.flash.handler.proto.LoginProto.FightStart.getDefaultInstance();
      }

      public org.qiunet.flash.handler.proto.LoginProto.FightStart build() {
        org.qiunet.flash.handler.proto.LoginProto.FightStart result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.qiunet.flash.handler.proto.LoginProto.FightStart buildPartial() {
        org.qiunet.flash.handler.proto.LoginProto.FightStart result = new org.qiunet.flash.handler.proto.LoginProto.FightStart(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          uids_ = java.util.Collections.unmodifiableList(uids_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.uids_ = uids_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.qiunet.flash.handler.proto.LoginProto.FightStart) {
          return mergeFrom((org.qiunet.flash.handler.proto.LoginProto.FightStart)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.qiunet.flash.handler.proto.LoginProto.FightStart other) {
        if (other == org.qiunet.flash.handler.proto.LoginProto.FightStart.getDefaultInstance()) return this;
        if (!other.uids_.isEmpty()) {
          if (uids_.isEmpty()) {
            uids_ = other.uids_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUidsIsMutable();
            uids_.addAll(other.uids_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.qiunet.flash.handler.proto.LoginProto.FightStart parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.qiunet.flash.handler.proto.LoginProto.FightStart) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> uids_ = java.util.Collections.emptyList();
      private void ensureUidsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          uids_ = new java.util.ArrayList<java.lang.Integer>(uids_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 战斗的人
       * </pre>
       *
       * <code>repeated int32 uids = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getUidsList() {
        return java.util.Collections.unmodifiableList(uids_);
      }
      /**
       * <pre>
       * 战斗的人
       * </pre>
       *
       * <code>repeated int32 uids = 1;</code>
       */
      public int getUidsCount() {
        return uids_.size();
      }
      /**
       * <pre>
       * 战斗的人
       * </pre>
       *
       * <code>repeated int32 uids = 1;</code>
       */
      public int getUids(int index) {
        return uids_.get(index);
      }
      /**
       * <pre>
       * 战斗的人
       * </pre>
       *
       * <code>repeated int32 uids = 1;</code>
       */
      public Builder setUids(
          int index, int value) {
        ensureUidsIsMutable();
        uids_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 战斗的人
       * </pre>
       *
       * <code>repeated int32 uids = 1;</code>
       */
      public Builder addUids(int value) {
        ensureUidsIsMutable();
        uids_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 战斗的人
       * </pre>
       *
       * <code>repeated int32 uids = 1;</code>
       */
      public Builder addAllUids(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureUidsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, uids_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 战斗的人
       * </pre>
       *
       * <code>repeated int32 uids = 1;</code>
       */
      public Builder clearUids() {
        uids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:FightStart)
    }

    // @@protoc_insertion_point(class_scope:FightStart)
    private static final org.qiunet.flash.handler.proto.LoginProto.FightStart DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.qiunet.flash.handler.proto.LoginProto.FightStart();
    }

    public static org.qiunet.flash.handler.proto.LoginProto.FightStart getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FightStart>
        PARSER = new com.google.protobuf.AbstractParser<FightStart>() {
      public FightStart parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FightStart(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FightStart> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FightStart> getParserForType() {
      return PARSER;
    }

    public org.qiunet.flash.handler.proto.LoginProto.FightStart getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FightStart_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FightStart_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/login.proto\"-\n\014LoginRequest\022\016\n\006o" +
      "penid\030\001 \001(\t\022\r\n\005token\030\002 \001(\t\"2\n\rLoginRespo" +
      "nse\022\013\n\003uid\030\001 \001(\005\022\024\n\014needRegister\030\002 \001(\010\"\032" +
      "\n\nFightStart\022\014\n\004uids\030\001 \003(\005B,\n\036org.qiunet" +
      ".flash.handler.protoB\nLoginProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRequest_descriptor,
        new java.lang.String[] { "Openid", "Token", });
    internal_static_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginResponse_descriptor,
        new java.lang.String[] { "Uid", "NeedRegister", });
    internal_static_FightStart_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FightStart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FightStart_descriptor,
        new java.lang.String[] { "Uids", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
