// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginRoom.proto

package org.qiunet.test.proto;

public final class LoginRoomProto {
  private LoginRoomProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginRoomRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginRoomRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RequestHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.RequestHeader header = 1;</code>
     */
    org.qiunet.test.proto.HeaderProto.RequestHeader getHeader();
    /**
     * <code>.RequestHeader header = 1;</code>
     */
    org.qiunet.test.proto.HeaderProto.RequestHeaderOrBuilder getHeaderOrBuilder();
  }
  /**
   * Protobuf type {@code LoginRoomRequest}
   */
  public  static final class LoginRoomRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginRoomRequest)
      LoginRoomRequestOrBuilder {
    // Use LoginRoomRequest.newBuilder() to construct.
    private LoginRoomRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginRoomRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoginRoomRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.qiunet.test.proto.HeaderProto.RequestHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(org.qiunet.test.proto.HeaderProto.RequestHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qiunet.test.proto.LoginRoomProto.internal_static_LoginRoomRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qiunet.test.proto.LoginRoomProto.internal_static_LoginRoomRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest.class, org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private org.qiunet.test.proto.HeaderProto.RequestHeader header_;
    /**
     * <code>.RequestHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.RequestHeader header = 1;</code>
     */
    public org.qiunet.test.proto.HeaderProto.RequestHeader getHeader() {
      return header_ == null ? org.qiunet.test.proto.HeaderProto.RequestHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.RequestHeader header = 1;</code>
     */
    public org.qiunet.test.proto.HeaderProto.RequestHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest)) {
        return super.equals(obj);
      }
      org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest other = (org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginRoomRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginRoomRequest)
        org.qiunet.test.proto.LoginRoomProto.LoginRoomRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.qiunet.test.proto.LoginRoomProto.internal_static_LoginRoomRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.qiunet.test.proto.LoginRoomProto.internal_static_LoginRoomRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest.class, org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest.Builder.class);
      }

      // Construct using org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.qiunet.test.proto.LoginRoomProto.internal_static_LoginRoomRequest_descriptor;
      }

      public org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest getDefaultInstanceForType() {
        return org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest.getDefaultInstance();
      }

      public org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest build() {
        org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest buildPartial() {
        org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest result = new org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest) {
          return mergeFrom((org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest other) {
        if (other == org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.qiunet.test.proto.HeaderProto.RequestHeader header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.qiunet.test.proto.HeaderProto.RequestHeader, org.qiunet.test.proto.HeaderProto.RequestHeader.Builder, org.qiunet.test.proto.HeaderProto.RequestHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public org.qiunet.test.proto.HeaderProto.RequestHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? org.qiunet.test.proto.HeaderProto.RequestHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder setHeader(org.qiunet.test.proto.HeaderProto.RequestHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder setHeader(
          org.qiunet.test.proto.HeaderProto.RequestHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder mergeHeader(org.qiunet.test.proto.HeaderProto.RequestHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              org.qiunet.test.proto.HeaderProto.RequestHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public org.qiunet.test.proto.HeaderProto.RequestHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public org.qiunet.test.proto.HeaderProto.RequestHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              org.qiunet.test.proto.HeaderProto.RequestHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.qiunet.test.proto.HeaderProto.RequestHeader, org.qiunet.test.proto.HeaderProto.RequestHeader.Builder, org.qiunet.test.proto.HeaderProto.RequestHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.qiunet.test.proto.HeaderProto.RequestHeader, org.qiunet.test.proto.HeaderProto.RequestHeader.Builder, org.qiunet.test.proto.HeaderProto.RequestHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:LoginRoomRequest)
    }

    // @@protoc_insertion_point(class_scope:LoginRoomRequest)
    private static final org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest();
    }

    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginRoomRequest>
        PARSER = new com.google.protobuf.AbstractParser<LoginRoomRequest>() {
      public LoginRoomRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginRoomRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginRoomRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRoomRequest> getParserForType() {
      return PARSER;
    }

    public org.qiunet.test.proto.LoginRoomProto.LoginRoomRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginRoomResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginRoomResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    org.qiunet.test.proto.HeaderProto.ResponseHeader getHeader();
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    org.qiunet.test.proto.HeaderProto.ResponseHeaderOrBuilder getHeaderOrBuilder();
  }
  /**
   * <pre>
   * 登录请求响应
   * </pre>
   *
   * Protobuf type {@code LoginRoomResponse}
   */
  public  static final class LoginRoomResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginRoomResponse)
      LoginRoomResponseOrBuilder {
    // Use LoginRoomResponse.newBuilder() to construct.
    private LoginRoomResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginRoomResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoginRoomResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.qiunet.test.proto.HeaderProto.ResponseHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(org.qiunet.test.proto.HeaderProto.ResponseHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qiunet.test.proto.LoginRoomProto.internal_static_LoginRoomResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qiunet.test.proto.LoginRoomProto.internal_static_LoginRoomResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse.class, org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private org.qiunet.test.proto.HeaderProto.ResponseHeader header_;
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    public org.qiunet.test.proto.HeaderProto.ResponseHeader getHeader() {
      return header_ == null ? org.qiunet.test.proto.HeaderProto.ResponseHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    public org.qiunet.test.proto.HeaderProto.ResponseHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse)) {
        return super.equals(obj);
      }
      org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse other = (org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 登录请求响应
     * </pre>
     *
     * Protobuf type {@code LoginRoomResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginRoomResponse)
        org.qiunet.test.proto.LoginRoomProto.LoginRoomResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.qiunet.test.proto.LoginRoomProto.internal_static_LoginRoomResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.qiunet.test.proto.LoginRoomProto.internal_static_LoginRoomResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse.class, org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse.Builder.class);
      }

      // Construct using org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.qiunet.test.proto.LoginRoomProto.internal_static_LoginRoomResponse_descriptor;
      }

      public org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse getDefaultInstanceForType() {
        return org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse.getDefaultInstance();
      }

      public org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse build() {
        org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse buildPartial() {
        org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse result = new org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse) {
          return mergeFrom((org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse other) {
        if (other == org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.qiunet.test.proto.HeaderProto.ResponseHeader header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.qiunet.test.proto.HeaderProto.ResponseHeader, org.qiunet.test.proto.HeaderProto.ResponseHeader.Builder, org.qiunet.test.proto.HeaderProto.ResponseHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public org.qiunet.test.proto.HeaderProto.ResponseHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? org.qiunet.test.proto.HeaderProto.ResponseHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder setHeader(org.qiunet.test.proto.HeaderProto.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder setHeader(
          org.qiunet.test.proto.HeaderProto.ResponseHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder mergeHeader(org.qiunet.test.proto.HeaderProto.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              org.qiunet.test.proto.HeaderProto.ResponseHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public org.qiunet.test.proto.HeaderProto.ResponseHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public org.qiunet.test.proto.HeaderProto.ResponseHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              org.qiunet.test.proto.HeaderProto.ResponseHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.qiunet.test.proto.HeaderProto.ResponseHeader, org.qiunet.test.proto.HeaderProto.ResponseHeader.Builder, org.qiunet.test.proto.HeaderProto.ResponseHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.qiunet.test.proto.HeaderProto.ResponseHeader, org.qiunet.test.proto.HeaderProto.ResponseHeader.Builder, org.qiunet.test.proto.HeaderProto.ResponseHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:LoginRoomResponse)
    }

    // @@protoc_insertion_point(class_scope:LoginRoomResponse)
    private static final org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse();
    }

    public static org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginRoomResponse>
        PARSER = new com.google.protobuf.AbstractParser<LoginRoomResponse>() {
      public LoginRoomResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginRoomResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginRoomResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRoomResponse> getParserForType() {
      return PARSER;
    }

    public org.qiunet.test.proto.LoginRoomProto.LoginRoomResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRoomRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRoomRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRoomResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRoomResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017LoginRoom.proto\032\014Header.proto\"2\n\020Login" +
      "RoomRequest\022\036\n\006header\030\001 \001(\0132\016.RequestHea" +
      "der\"4\n\021LoginRoomResponse\022\037\n\006header\030\001 \001(\013" +
      "2\017.ResponseHeaderB\'\n\025org.qiunet.test.pro" +
      "toB\016LoginRoomProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.qiunet.test.proto.HeaderProto.getDescriptor(),
        }, assigner);
    internal_static_LoginRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRoomRequest_descriptor,
        new java.lang.String[] { "Header", });
    internal_static_LoginRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRoomResponse_descriptor,
        new java.lang.String[] { "Header", });
    org.qiunet.test.proto.HeaderProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
