// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerIndex.proto

package org.qiunet.test.proto;

public final class PlayerIndexProto {
  private PlayerIndexProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerIndexRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerIndexRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RequestHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.RequestHeader header = 1;</code>
     */
    org.qiunet.test.proto.HeaderProto.RequestHeader getHeader();
    /**
     * <code>.RequestHeader header = 1;</code>
     */
    org.qiunet.test.proto.HeaderProto.RequestHeaderOrBuilder getHeaderOrBuilder();
  }
  /**
   * Protobuf type {@code PlayerIndexRequest}
   */
  public  static final class PlayerIndexRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerIndexRequest)
      PlayerIndexRequestOrBuilder {
    // Use PlayerIndexRequest.newBuilder() to construct.
    private PlayerIndexRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerIndexRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PlayerIndexRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.qiunet.test.proto.HeaderProto.RequestHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(org.qiunet.test.proto.HeaderProto.RequestHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qiunet.test.proto.PlayerIndexProto.internal_static_PlayerIndexRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qiunet.test.proto.PlayerIndexProto.internal_static_PlayerIndexRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest.class, org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private org.qiunet.test.proto.HeaderProto.RequestHeader header_;
    /**
     * <code>.RequestHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.RequestHeader header = 1;</code>
     */
    public org.qiunet.test.proto.HeaderProto.RequestHeader getHeader() {
      return header_ == null ? org.qiunet.test.proto.HeaderProto.RequestHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.RequestHeader header = 1;</code>
     */
    public org.qiunet.test.proto.HeaderProto.RequestHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest)) {
        return super.equals(obj);
      }
      org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest other = (org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerIndexRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerIndexRequest)
        org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.qiunet.test.proto.PlayerIndexProto.internal_static_PlayerIndexRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.qiunet.test.proto.PlayerIndexProto.internal_static_PlayerIndexRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest.class, org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest.Builder.class);
      }

      // Construct using org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.qiunet.test.proto.PlayerIndexProto.internal_static_PlayerIndexRequest_descriptor;
      }

      public org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest getDefaultInstanceForType() {
        return org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest.getDefaultInstance();
      }

      public org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest build() {
        org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest buildPartial() {
        org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest result = new org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest) {
          return mergeFrom((org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest other) {
        if (other == org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.qiunet.test.proto.HeaderProto.RequestHeader header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.qiunet.test.proto.HeaderProto.RequestHeader, org.qiunet.test.proto.HeaderProto.RequestHeader.Builder, org.qiunet.test.proto.HeaderProto.RequestHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public org.qiunet.test.proto.HeaderProto.RequestHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? org.qiunet.test.proto.HeaderProto.RequestHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder setHeader(org.qiunet.test.proto.HeaderProto.RequestHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder setHeader(
          org.qiunet.test.proto.HeaderProto.RequestHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder mergeHeader(org.qiunet.test.proto.HeaderProto.RequestHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              org.qiunet.test.proto.HeaderProto.RequestHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public org.qiunet.test.proto.HeaderProto.RequestHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public org.qiunet.test.proto.HeaderProto.RequestHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              org.qiunet.test.proto.HeaderProto.RequestHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.RequestHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.qiunet.test.proto.HeaderProto.RequestHeader, org.qiunet.test.proto.HeaderProto.RequestHeader.Builder, org.qiunet.test.proto.HeaderProto.RequestHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.qiunet.test.proto.HeaderProto.RequestHeader, org.qiunet.test.proto.HeaderProto.RequestHeader.Builder, org.qiunet.test.proto.HeaderProto.RequestHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PlayerIndexRequest)
    }

    // @@protoc_insertion_point(class_scope:PlayerIndexRequest)
    private static final org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest();
    }

    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerIndexRequest>
        PARSER = new com.google.protobuf.AbstractParser<PlayerIndexRequest>() {
      public PlayerIndexRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlayerIndexRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerIndexRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerIndexRequest> getParserForType() {
      return PARSER;
    }

    public org.qiunet.test.proto.PlayerIndexProto.PlayerIndexRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerIndexResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerIndexResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    org.qiunet.test.proto.HeaderProto.ResponseHeader getHeader();
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    org.qiunet.test.proto.HeaderProto.ResponseHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>repeated .Item items = 2;</code>
     */
    java.util.List<org.qiunet.test.proto.PlayerIndexProto.Item> 
        getItemsList();
    /**
     * <code>repeated .Item items = 2;</code>
     */
    org.qiunet.test.proto.PlayerIndexProto.Item getItems(int index);
    /**
     * <code>repeated .Item items = 2;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .Item items = 2;</code>
     */
    java.util.List<? extends org.qiunet.test.proto.PlayerIndexProto.ItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .Item items = 2;</code>
     */
    org.qiunet.test.proto.PlayerIndexProto.ItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * <pre>
   ** 登录请求响应 *
   * </pre>
   *
   * Protobuf type {@code PlayerIndexResponse}
   */
  public  static final class PlayerIndexResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerIndexResponse)
      PlayerIndexResponseOrBuilder {
    // Use PlayerIndexResponse.newBuilder() to construct.
    private PlayerIndexResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerIndexResponse() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PlayerIndexResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.qiunet.test.proto.HeaderProto.ResponseHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(org.qiunet.test.proto.HeaderProto.ResponseHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                items_ = new java.util.ArrayList<org.qiunet.test.proto.PlayerIndexProto.Item>();
                mutable_bitField0_ |= 0x00000002;
              }
              items_.add(
                  input.readMessage(org.qiunet.test.proto.PlayerIndexProto.Item.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qiunet.test.proto.PlayerIndexProto.internal_static_PlayerIndexResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qiunet.test.proto.PlayerIndexProto.internal_static_PlayerIndexResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse.class, org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse.Builder.class);
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private org.qiunet.test.proto.HeaderProto.ResponseHeader header_;
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    public org.qiunet.test.proto.HeaderProto.ResponseHeader getHeader() {
      return header_ == null ? org.qiunet.test.proto.HeaderProto.ResponseHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    public org.qiunet.test.proto.HeaderProto.ResponseHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int ITEMS_FIELD_NUMBER = 2;
    private java.util.List<org.qiunet.test.proto.PlayerIndexProto.Item> items_;
    /**
     * <code>repeated .Item items = 2;</code>
     */
    public java.util.List<org.qiunet.test.proto.PlayerIndexProto.Item> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .Item items = 2;</code>
     */
    public java.util.List<? extends org.qiunet.test.proto.PlayerIndexProto.ItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .Item items = 2;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .Item items = 2;</code>
     */
    public org.qiunet.test.proto.PlayerIndexProto.Item getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .Item items = 2;</code>
     */
    public org.qiunet.test.proto.PlayerIndexProto.ItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(2, items_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, items_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse)) {
        return super.equals(obj);
      }
      org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse other = (org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && getItemsList()
          .equals(other.getItemsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 登录请求响应 *
     * </pre>
     *
     * Protobuf type {@code PlayerIndexResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerIndexResponse)
        org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.qiunet.test.proto.PlayerIndexProto.internal_static_PlayerIndexResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.qiunet.test.proto.PlayerIndexProto.internal_static_PlayerIndexResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse.class, org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse.Builder.class);
      }

      // Construct using org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.qiunet.test.proto.PlayerIndexProto.internal_static_PlayerIndexResponse_descriptor;
      }

      public org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse getDefaultInstanceForType() {
        return org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse.getDefaultInstance();
      }

      public org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse build() {
        org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse buildPartial() {
        org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse result = new org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse) {
          return mergeFrom((org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse other) {
        if (other == org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.qiunet.test.proto.HeaderProto.ResponseHeader header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.qiunet.test.proto.HeaderProto.ResponseHeader, org.qiunet.test.proto.HeaderProto.ResponseHeader.Builder, org.qiunet.test.proto.HeaderProto.ResponseHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public org.qiunet.test.proto.HeaderProto.ResponseHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? org.qiunet.test.proto.HeaderProto.ResponseHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder setHeader(org.qiunet.test.proto.HeaderProto.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder setHeader(
          org.qiunet.test.proto.HeaderProto.ResponseHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder mergeHeader(org.qiunet.test.proto.HeaderProto.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              org.qiunet.test.proto.HeaderProto.ResponseHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public org.qiunet.test.proto.HeaderProto.ResponseHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public org.qiunet.test.proto.HeaderProto.ResponseHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              org.qiunet.test.proto.HeaderProto.ResponseHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.qiunet.test.proto.HeaderProto.ResponseHeader, org.qiunet.test.proto.HeaderProto.ResponseHeader.Builder, org.qiunet.test.proto.HeaderProto.ResponseHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.qiunet.test.proto.HeaderProto.ResponseHeader, org.qiunet.test.proto.HeaderProto.ResponseHeader.Builder, org.qiunet.test.proto.HeaderProto.ResponseHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.util.List<org.qiunet.test.proto.PlayerIndexProto.Item> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          items_ = new java.util.ArrayList<org.qiunet.test.proto.PlayerIndexProto.Item>(items_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.qiunet.test.proto.PlayerIndexProto.Item, org.qiunet.test.proto.PlayerIndexProto.Item.Builder, org.qiunet.test.proto.PlayerIndexProto.ItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .Item items = 2;</code>
       */
      public java.util.List<org.qiunet.test.proto.PlayerIndexProto.Item> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public org.qiunet.test.proto.PlayerIndexProto.Item getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public Builder setItems(
          int index, org.qiunet.test.proto.PlayerIndexProto.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public Builder setItems(
          int index, org.qiunet.test.proto.PlayerIndexProto.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public Builder addItems(org.qiunet.test.proto.PlayerIndexProto.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public Builder addItems(
          int index, org.qiunet.test.proto.PlayerIndexProto.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public Builder addItems(
          org.qiunet.test.proto.PlayerIndexProto.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public Builder addItems(
          int index, org.qiunet.test.proto.PlayerIndexProto.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends org.qiunet.test.proto.PlayerIndexProto.Item> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public org.qiunet.test.proto.PlayerIndexProto.Item.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public org.qiunet.test.proto.PlayerIndexProto.ItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public java.util.List<? extends org.qiunet.test.proto.PlayerIndexProto.ItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public org.qiunet.test.proto.PlayerIndexProto.Item.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            org.qiunet.test.proto.PlayerIndexProto.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public org.qiunet.test.proto.PlayerIndexProto.Item.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, org.qiunet.test.proto.PlayerIndexProto.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .Item items = 2;</code>
       */
      public java.util.List<org.qiunet.test.proto.PlayerIndexProto.Item.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.qiunet.test.proto.PlayerIndexProto.Item, org.qiunet.test.proto.PlayerIndexProto.Item.Builder, org.qiunet.test.proto.PlayerIndexProto.ItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.qiunet.test.proto.PlayerIndexProto.Item, org.qiunet.test.proto.PlayerIndexProto.Item.Builder, org.qiunet.test.proto.PlayerIndexProto.ItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PlayerIndexResponse)
    }

    // @@protoc_insertion_point(class_scope:PlayerIndexResponse)
    private static final org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse();
    }

    public static org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerIndexResponse>
        PARSER = new com.google.protobuf.AbstractParser<PlayerIndexResponse>() {
      public PlayerIndexResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlayerIndexResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerIndexResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerIndexResponse> getParserForType() {
      return PARSER;
    }

    public org.qiunet.test.proto.PlayerIndexProto.PlayerIndexResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Item)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 item_id = 1;</code>
     */
    int getItemId();

    /**
     * <code>int32 count = 2;</code>
     */
    int getCount();
  }
  /**
   * <pre>
   ** 道具 
   * </pre>
   *
   * Protobuf type {@code Item}
   */
  public  static final class Item extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Item)
      ItemOrBuilder {
    // Use Item.newBuilder() to construct.
    private Item(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Item() {
      itemId_ = 0;
      count_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Item(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              itemId_ = input.readInt32();
              break;
            }
            case 16: {

              count_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qiunet.test.proto.PlayerIndexProto.internal_static_Item_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qiunet.test.proto.PlayerIndexProto.internal_static_Item_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qiunet.test.proto.PlayerIndexProto.Item.class, org.qiunet.test.proto.PlayerIndexProto.Item.Builder.class);
    }

    public static final int ITEM_ID_FIELD_NUMBER = 1;
    private int itemId_;
    /**
     * <code>int32 item_id = 1;</code>
     */
    public int getItemId() {
      return itemId_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>int32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (itemId_ != 0) {
        output.writeInt32(1, itemId_);
      }
      if (count_ != 0) {
        output.writeInt32(2, count_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (itemId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, itemId_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.qiunet.test.proto.PlayerIndexProto.Item)) {
        return super.equals(obj);
      }
      org.qiunet.test.proto.PlayerIndexProto.Item other = (org.qiunet.test.proto.PlayerIndexProto.Item) obj;

      boolean result = true;
      result = result && (getItemId()
          == other.getItemId());
      result = result && (getCount()
          == other.getCount());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ITEM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getItemId();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.qiunet.test.proto.PlayerIndexProto.Item parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.Item parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.Item parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.Item parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.Item parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.Item parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.Item parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.Item parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.Item parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.qiunet.test.proto.PlayerIndexProto.Item parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.qiunet.test.proto.PlayerIndexProto.Item prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 道具 
     * </pre>
     *
     * Protobuf type {@code Item}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Item)
        org.qiunet.test.proto.PlayerIndexProto.ItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.qiunet.test.proto.PlayerIndexProto.internal_static_Item_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.qiunet.test.proto.PlayerIndexProto.internal_static_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.qiunet.test.proto.PlayerIndexProto.Item.class, org.qiunet.test.proto.PlayerIndexProto.Item.Builder.class);
      }

      // Construct using org.qiunet.test.proto.PlayerIndexProto.Item.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        itemId_ = 0;

        count_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.qiunet.test.proto.PlayerIndexProto.internal_static_Item_descriptor;
      }

      public org.qiunet.test.proto.PlayerIndexProto.Item getDefaultInstanceForType() {
        return org.qiunet.test.proto.PlayerIndexProto.Item.getDefaultInstance();
      }

      public org.qiunet.test.proto.PlayerIndexProto.Item build() {
        org.qiunet.test.proto.PlayerIndexProto.Item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.qiunet.test.proto.PlayerIndexProto.Item buildPartial() {
        org.qiunet.test.proto.PlayerIndexProto.Item result = new org.qiunet.test.proto.PlayerIndexProto.Item(this);
        result.itemId_ = itemId_;
        result.count_ = count_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.qiunet.test.proto.PlayerIndexProto.Item) {
          return mergeFrom((org.qiunet.test.proto.PlayerIndexProto.Item)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.qiunet.test.proto.PlayerIndexProto.Item other) {
        if (other == org.qiunet.test.proto.PlayerIndexProto.Item.getDefaultInstance()) return this;
        if (other.getItemId() != 0) {
          setItemId(other.getItemId());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.qiunet.test.proto.PlayerIndexProto.Item parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.qiunet.test.proto.PlayerIndexProto.Item) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int itemId_ ;
      /**
       * <code>int32 item_id = 1;</code>
       */
      public int getItemId() {
        return itemId_;
      }
      /**
       * <code>int32 item_id = 1;</code>
       */
      public Builder setItemId(int value) {
        
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 item_id = 1;</code>
       */
      public Builder clearItemId() {
        
        itemId_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>int32 count = 2;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 count = 2;</code>
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count = 2;</code>
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Item)
    }

    // @@protoc_insertion_point(class_scope:Item)
    private static final org.qiunet.test.proto.PlayerIndexProto.Item DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.qiunet.test.proto.PlayerIndexProto.Item();
    }

    public static org.qiunet.test.proto.PlayerIndexProto.Item getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Item>
        PARSER = new com.google.protobuf.AbstractParser<Item>() {
      public Item parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Item(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Item> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Item> getParserForType() {
      return PARSER;
    }

    public org.qiunet.test.proto.PlayerIndexProto.Item getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerIndexRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerIndexRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerIndexResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerIndexResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Item_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PlayerIndex.proto\032\014Header.proto\"4\n\022Pla" +
      "yerIndexRequest\022\036\n\006header\030\001 \001(\0132\016.Reques" +
      "tHeader\"L\n\023PlayerIndexResponse\022\037\n\006header" +
      "\030\001 \001(\0132\017.ResponseHeader\022\024\n\005items\030\002 \003(\0132\005" +
      ".Item\"&\n\004Item\022\017\n\007item_id\030\001 \001(\005\022\r\n\005count\030" +
      "\002 \001(\005B)\n\025org.qiunet.test.protoB\020PlayerIn" +
      "dexProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.qiunet.test.proto.HeaderProto.getDescriptor(),
        }, assigner);
    internal_static_PlayerIndexRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerIndexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerIndexRequest_descriptor,
        new java.lang.String[] { "Header", });
    internal_static_PlayerIndexResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PlayerIndexResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerIndexResponse_descriptor,
        new java.lang.String[] { "Header", "Items", });
    internal_static_Item_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Item_descriptor,
        new java.lang.String[] { "ItemId", "Count", });
    org.qiunet.test.proto.HeaderProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
