package org.qiunet.excel2cfgs.swing.panel;

import com.intellij.uiDesigner.core.GridLayoutManager;
import org.qiunet.excel2cfgs.swing.component.IconJPanel;
import org.qiunet.excel2cfgs.swing.enums.IconButtonType;

import javax.swing.*;
import java.awt.*;

/***
 * json 格式化的面板
 * @Author qiunet
 * @Date 2021/2/9 21:57
 **/
public class JsonFormatPanel extends IconJPanel {

    private JPanel showPanel;

    @Override
    public void unActivate() {

    }

    @Override
    public void activate() {

    }


    @Override
    public IconButtonType type() {
        return IconButtonType.json;
    }

    @Override
    public JPanel getShowPanel() {
        return showPanel;
    }

    @Override
    public void addToParent(ToolTabPanel toolTabPanel) {
        toolTabPanel.getPanelUp().add(this.getButton());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        showPanel = new JPanel();
        showPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return showPanel;
    }
}
